/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace CropMarketplace {
  export type CropStruct = {
    id: BigNumberish;
    farmerWallet: AddressLike;
    farmerBankAccount: string;
    name: string;
    quantity: BigNumberish;
    quality: string;
    pricePerKg: BigNumberish;
    imageHash: string;
    timestamp: BigNumberish;
    sold: boolean;
  };

  export type CropStructOutput = [
    id: bigint,
    farmerWallet: string,
    farmerBankAccount: string,
    name: string,
    quantity: bigint,
    quality: string,
    pricePerKg: bigint,
    imageHash: string,
    timestamp: bigint,
    sold: boolean
  ] & {
    id: bigint;
    farmerWallet: string;
    farmerBankAccount: string;
    name: string;
    quantity: bigint;
    quality: string;
    pricePerKg: bigint;
    imageHash: string;
    timestamp: bigint;
    sold: boolean;
  };

  export type OfferStruct = {
    id: BigNumberish;
    cropId: BigNumberish;
    buyerWallet: AddressLike;
    buyerBankAccount: string;
    offerPrice: BigNumberish;
    timestamp: BigNumberish;
    accepted: boolean;
    rejected: boolean;
  };

  export type OfferStructOutput = [
    id: bigint,
    cropId: bigint,
    buyerWallet: string,
    buyerBankAccount: string,
    offerPrice: bigint,
    timestamp: bigint,
    accepted: boolean,
    rejected: boolean
  ] & {
    id: bigint;
    cropId: bigint;
    buyerWallet: string;
    buyerBankAccount: string;
    offerPrice: bigint;
    timestamp: bigint;
    accepted: boolean;
    rejected: boolean;
  };

  export type PaymentRecordStruct = {
    offerId: BigNumberish;
    amount: BigNumberish;
    paymentMethod: string;
    transactionId: string;
    initiatedAt: BigNumberish;
    completedAt: BigNumberish;
    status: string;
  };

  export type PaymentRecordStructOutput = [
    offerId: bigint,
    amount: bigint,
    paymentMethod: string,
    transactionId: string,
    initiatedAt: bigint,
    completedAt: bigint,
    status: string
  ] & {
    offerId: bigint;
    amount: bigint;
    paymentMethod: string;
    transactionId: string;
    initiatedAt: bigint;
    completedAt: bigint;
    status: string;
  };
}

export interface CropMarketplaceInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "acceptOffer"
      | "commitPayment"
      | "confirmPayment"
      | "cropCount"
      | "crops"
      | "getCrop"
      | "getOffer"
      | "getPayment"
      | "listCrop"
      | "makeOffer"
      | "offerCount"
      | "offers"
      | "payments"
      | "rejectOffer"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "CropListed"
      | "OfferAccepted"
      | "OfferMade"
      | "OfferRejected"
      | "PaymentCommitted"
      | "PaymentCompleted"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "acceptOffer",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "commitPayment",
    values: [BigNumberish, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "confirmPayment",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(functionFragment: "cropCount", values?: undefined): string;
  encodeFunctionData(functionFragment: "crops", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "getCrop",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getOffer",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getPayment",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "listCrop",
    values: [string, string, BigNumberish, string, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "makeOffer",
    values: [BigNumberish, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "offerCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "offers",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "payments",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "rejectOffer",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "acceptOffer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "commitPayment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "confirmPayment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "cropCount", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "crops", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getCrop", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getOffer", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getPayment", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "listCrop", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "makeOffer", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "offerCount", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "offers", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "payments", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "rejectOffer",
    data: BytesLike
  ): Result;
}

export namespace CropListedEvent {
  export type InputTuple = [
    cropId: BigNumberish,
    farmer: AddressLike,
    name: string,
    price: BigNumberish,
    bankAccount: string
  ];
  export type OutputTuple = [
    cropId: bigint,
    farmer: string,
    name: string,
    price: bigint,
    bankAccount: string
  ];
  export interface OutputObject {
    cropId: bigint;
    farmer: string;
    name: string;
    price: bigint;
    bankAccount: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OfferAcceptedEvent {
  export type InputTuple = [offerId: BigNumberish, cropId: BigNumberish];
  export type OutputTuple = [offerId: bigint, cropId: bigint];
  export interface OutputObject {
    offerId: bigint;
    cropId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OfferMadeEvent {
  export type InputTuple = [
    offerId: BigNumberish,
    cropId: BigNumberish,
    buyer: AddressLike,
    price: BigNumberish
  ];
  export type OutputTuple = [
    offerId: bigint,
    cropId: bigint,
    buyer: string,
    price: bigint
  ];
  export interface OutputObject {
    offerId: bigint;
    cropId: bigint;
    buyer: string;
    price: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OfferRejectedEvent {
  export type InputTuple = [offerId: BigNumberish];
  export type OutputTuple = [offerId: bigint];
  export interface OutputObject {
    offerId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PaymentCommittedEvent {
  export type InputTuple = [
    offerId: BigNumberish,
    amount: BigNumberish,
    paymentMethod: string,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    offerId: bigint,
    amount: bigint,
    paymentMethod: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    offerId: bigint;
    amount: bigint;
    paymentMethod: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PaymentCompletedEvent {
  export type InputTuple = [
    offerId: BigNumberish,
    transactionId: string,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    offerId: bigint,
    transactionId: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    offerId: bigint;
    transactionId: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface CropMarketplace extends BaseContract {
  connect(runner?: ContractRunner | null): CropMarketplace;
  waitForDeployment(): Promise<this>;

  interface: CropMarketplaceInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  acceptOffer: TypedContractMethod<
    [_offerId: BigNumberish],
    [void],
    "nonpayable"
  >;

  commitPayment: TypedContractMethod<
    [_offerId: BigNumberish, _amount: BigNumberish, _paymentMethod: string],
    [void],
    "nonpayable"
  >;

  confirmPayment: TypedContractMethod<
    [_offerId: BigNumberish, _transactionId: string],
    [void],
    "nonpayable"
  >;

  cropCount: TypedContractMethod<[], [bigint], "view">;

  crops: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        string,
        bigint,
        string,
        bigint,
        string,
        bigint,
        boolean
      ] & {
        id: bigint;
        farmerWallet: string;
        farmerBankAccount: string;
        name: string;
        quantity: bigint;
        quality: string;
        pricePerKg: bigint;
        imageHash: string;
        timestamp: bigint;
        sold: boolean;
      }
    ],
    "view"
  >;

  getCrop: TypedContractMethod<
    [_cropId: BigNumberish],
    [CropMarketplace.CropStructOutput],
    "view"
  >;

  getOffer: TypedContractMethod<
    [_offerId: BigNumberish],
    [CropMarketplace.OfferStructOutput],
    "view"
  >;

  getPayment: TypedContractMethod<
    [_offerId: BigNumberish],
    [CropMarketplace.PaymentRecordStructOutput],
    "view"
  >;

  listCrop: TypedContractMethod<
    [
      _farmerBankAccount: string,
      _name: string,
      _quantity: BigNumberish,
      _quality: string,
      _pricePerKg: BigNumberish,
      _imageHash: string
    ],
    [bigint],
    "nonpayable"
  >;

  makeOffer: TypedContractMethod<
    [
      _cropId: BigNumberish,
      _offerPrice: BigNumberish,
      _buyerBankAccount: string
    ],
    [bigint],
    "nonpayable"
  >;

  offerCount: TypedContractMethod<[], [bigint], "view">;

  offers: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, string, string, bigint, bigint, boolean, boolean] & {
        id: bigint;
        cropId: bigint;
        buyerWallet: string;
        buyerBankAccount: string;
        offerPrice: bigint;
        timestamp: bigint;
        accepted: boolean;
        rejected: boolean;
      }
    ],
    "view"
  >;

  payments: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, string, string, bigint, bigint, string] & {
        offerId: bigint;
        amount: bigint;
        paymentMethod: string;
        transactionId: string;
        initiatedAt: bigint;
        completedAt: bigint;
        status: string;
      }
    ],
    "view"
  >;

  rejectOffer: TypedContractMethod<
    [_offerId: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "acceptOffer"
  ): TypedContractMethod<[_offerId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "commitPayment"
  ): TypedContractMethod<
    [_offerId: BigNumberish, _amount: BigNumberish, _paymentMethod: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "confirmPayment"
  ): TypedContractMethod<
    [_offerId: BigNumberish, _transactionId: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "cropCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "crops"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        string,
        bigint,
        string,
        bigint,
        string,
        bigint,
        boolean
      ] & {
        id: bigint;
        farmerWallet: string;
        farmerBankAccount: string;
        name: string;
        quantity: bigint;
        quality: string;
        pricePerKg: bigint;
        imageHash: string;
        timestamp: bigint;
        sold: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getCrop"
  ): TypedContractMethod<
    [_cropId: BigNumberish],
    [CropMarketplace.CropStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getOffer"
  ): TypedContractMethod<
    [_offerId: BigNumberish],
    [CropMarketplace.OfferStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPayment"
  ): TypedContractMethod<
    [_offerId: BigNumberish],
    [CropMarketplace.PaymentRecordStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "listCrop"
  ): TypedContractMethod<
    [
      _farmerBankAccount: string,
      _name: string,
      _quantity: BigNumberish,
      _quality: string,
      _pricePerKg: BigNumberish,
      _imageHash: string
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "makeOffer"
  ): TypedContractMethod<
    [
      _cropId: BigNumberish,
      _offerPrice: BigNumberish,
      _buyerBankAccount: string
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "offerCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "offers"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, string, string, bigint, bigint, boolean, boolean] & {
        id: bigint;
        cropId: bigint;
        buyerWallet: string;
        buyerBankAccount: string;
        offerPrice: bigint;
        timestamp: bigint;
        accepted: boolean;
        rejected: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "payments"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, string, string, bigint, bigint, string] & {
        offerId: bigint;
        amount: bigint;
        paymentMethod: string;
        transactionId: string;
        initiatedAt: bigint;
        completedAt: bigint;
        status: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "rejectOffer"
  ): TypedContractMethod<[_offerId: BigNumberish], [void], "nonpayable">;

  getEvent(
    key: "CropListed"
  ): TypedContractEvent<
    CropListedEvent.InputTuple,
    CropListedEvent.OutputTuple,
    CropListedEvent.OutputObject
  >;
  getEvent(
    key: "OfferAccepted"
  ): TypedContractEvent<
    OfferAcceptedEvent.InputTuple,
    OfferAcceptedEvent.OutputTuple,
    OfferAcceptedEvent.OutputObject
  >;
  getEvent(
    key: "OfferMade"
  ): TypedContractEvent<
    OfferMadeEvent.InputTuple,
    OfferMadeEvent.OutputTuple,
    OfferMadeEvent.OutputObject
  >;
  getEvent(
    key: "OfferRejected"
  ): TypedContractEvent<
    OfferRejectedEvent.InputTuple,
    OfferRejectedEvent.OutputTuple,
    OfferRejectedEvent.OutputObject
  >;
  getEvent(
    key: "PaymentCommitted"
  ): TypedContractEvent<
    PaymentCommittedEvent.InputTuple,
    PaymentCommittedEvent.OutputTuple,
    PaymentCommittedEvent.OutputObject
  >;
  getEvent(
    key: "PaymentCompleted"
  ): TypedContractEvent<
    PaymentCompletedEvent.InputTuple,
    PaymentCompletedEvent.OutputTuple,
    PaymentCompletedEvent.OutputObject
  >;

  filters: {
    "CropListed(uint256,address,string,uint256,string)": TypedContractEvent<
      CropListedEvent.InputTuple,
      CropListedEvent.OutputTuple,
      CropListedEvent.OutputObject
    >;
    CropListed: TypedContractEvent<
      CropListedEvent.InputTuple,
      CropListedEvent.OutputTuple,
      CropListedEvent.OutputObject
    >;

    "OfferAccepted(uint256,uint256)": TypedContractEvent<
      OfferAcceptedEvent.InputTuple,
      OfferAcceptedEvent.OutputTuple,
      OfferAcceptedEvent.OutputObject
    >;
    OfferAccepted: TypedContractEvent<
      OfferAcceptedEvent.InputTuple,
      OfferAcceptedEvent.OutputTuple,
      OfferAcceptedEvent.OutputObject
    >;

    "OfferMade(uint256,uint256,address,uint256)": TypedContractEvent<
      OfferMadeEvent.InputTuple,
      OfferMadeEvent.OutputTuple,
      OfferMadeEvent.OutputObject
    >;
    OfferMade: TypedContractEvent<
      OfferMadeEvent.InputTuple,
      OfferMadeEvent.OutputTuple,
      OfferMadeEvent.OutputObject
    >;

    "OfferRejected(uint256)": TypedContractEvent<
      OfferRejectedEvent.InputTuple,
      OfferRejectedEvent.OutputTuple,
      OfferRejectedEvent.OutputObject
    >;
    OfferRejected: TypedContractEvent<
      OfferRejectedEvent.InputTuple,
      OfferRejectedEvent.OutputTuple,
      OfferRejectedEvent.OutputObject
    >;

    "PaymentCommitted(uint256,uint256,string,uint256)": TypedContractEvent<
      PaymentCommittedEvent.InputTuple,
      PaymentCommittedEvent.OutputTuple,
      PaymentCommittedEvent.OutputObject
    >;
    PaymentCommitted: TypedContractEvent<
      PaymentCommittedEvent.InputTuple,
      PaymentCommittedEvent.OutputTuple,
      PaymentCommittedEvent.OutputObject
    >;

    "PaymentCompleted(uint256,string,uint256)": TypedContractEvent<
      PaymentCompletedEvent.InputTuple,
      PaymentCompletedEvent.OutputTuple,
      PaymentCompletedEvent.OutputObject
    >;
    PaymentCompleted: TypedContractEvent<
      PaymentCompletedEvent.InputTuple,
      PaymentCompletedEvent.OutputTuple,
      PaymentCompletedEvent.OutputObject
    >;
  };
}
