/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface PriceOracleInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "admin"
      | "getMandiPrice"
      | "getMinAllowedPrice"
      | "mandiPrices"
      | "setMandiPrice"
      | "validateOffer"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "PriceUpdated"): EventFragment;

  encodeFunctionData(functionFragment: "admin", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getMandiPrice",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getMinAllowedPrice",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "mandiPrices", values: [string]): string;
  encodeFunctionData(
    functionFragment: "setMandiPrice",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "validateOffer",
    values: [string, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "admin", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getMandiPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMinAllowedPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "mandiPrices",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setMandiPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "validateOffer",
    data: BytesLike
  ): Result;
}

export namespace PriceUpdatedEvent {
  export type InputTuple = [cropName: string, price: BigNumberish];
  export type OutputTuple = [cropName: string, price: bigint];
  export interface OutputObject {
    cropName: string;
    price: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface PriceOracle extends BaseContract {
  connect(runner?: ContractRunner | null): PriceOracle;
  waitForDeployment(): Promise<this>;

  interface: PriceOracleInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  admin: TypedContractMethod<[], [string], "view">;

  getMandiPrice: TypedContractMethod<[_cropName: string], [bigint], "view">;

  getMinAllowedPrice: TypedContractMethod<
    [_cropName: string],
    [bigint],
    "view"
  >;

  mandiPrices: TypedContractMethod<[arg0: string], [bigint], "view">;

  setMandiPrice: TypedContractMethod<
    [_cropName: string, _price: BigNumberish],
    [void],
    "nonpayable"
  >;

  validateOffer: TypedContractMethod<
    [_cropName: string, _offerPrice: BigNumberish],
    [boolean],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "admin"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getMandiPrice"
  ): TypedContractMethod<[_cropName: string], [bigint], "view">;
  getFunction(
    nameOrSignature: "getMinAllowedPrice"
  ): TypedContractMethod<[_cropName: string], [bigint], "view">;
  getFunction(
    nameOrSignature: "mandiPrices"
  ): TypedContractMethod<[arg0: string], [bigint], "view">;
  getFunction(
    nameOrSignature: "setMandiPrice"
  ): TypedContractMethod<
    [_cropName: string, _price: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "validateOffer"
  ): TypedContractMethod<
    [_cropName: string, _offerPrice: BigNumberish],
    [boolean],
    "view"
  >;

  getEvent(
    key: "PriceUpdated"
  ): TypedContractEvent<
    PriceUpdatedEvent.InputTuple,
    PriceUpdatedEvent.OutputTuple,
    PriceUpdatedEvent.OutputObject
  >;

  filters: {
    "PriceUpdated(string,uint256)": TypedContractEvent<
      PriceUpdatedEvent.InputTuple,
      PriceUpdatedEvent.OutputTuple,
      PriceUpdatedEvent.OutputObject
    >;
    PriceUpdated: TypedContractEvent<
      PriceUpdatedEvent.InputTuple,
      PriceUpdatedEvent.OutputTuple,
      PriceUpdatedEvent.OutputObject
    >;
  };
}
